name: apk ğŸ•Šï¸
on:
  repository_dispatch:
    types: [build-apk]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Web URL
        id: geturl
        run: |
          if [ "${{ github.event_name }}" = "repository_dispatch" ]; then
            echo "::set-output name=weburl::${{ github.event.client_payload.url }}"
          else
            echo "::set-output name=weburl::https://your-default-pwa-url.com"
          fi
      - uses: darkshredder/web-to-app-action@main
        with:
          build-folder-path: "build"
          app-name: "Your-App-Name"
          output-folder-path: "my-apks"
          url: ${{ steps.geturl.outputs.weburl }}
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: Final-apks
          path: my-apks/
